---
id: 201711-decentralized-data-management
base_name: 201711-decentralized-data-management
tags:
- rabbit
- microservices
- decentralized data management
- polyglot persistence
presentation_date: 2017-12-01
version: 2017.11.10.1
licenses:
- MIT
slideshare_id:
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Giovanni Sakti
  email: giosakti@gmail.com
  rubygems_user: giosakti
  slideshare_user:
  speaker_deck_user: giosakti 
